import './globals.css'

// Temporarily using system fonts due to Google Fonts connectivity issues
const inter = {
  className: 'font-sans'
}

export const metadata = {
  title: 'Valeria Muhembele Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
